services:
  listener.requestresponse:
    class: ProxyBundle\Listener\ProxyListener
    arguments: []
    tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
